### ISSUE TITLE
Default browser outline looks ugly

### ISSUE THREAD

**Issue by igorcafe** [tonik/theme#106]
![image](https://user-images.githubusercontent.com/85039990/139700014-59cce583-e409-482c-8aa4-9d62724c6446.png)
![image](https://user-images.githubusercontent.com/85039990/139700847-1602a6df-c85b-484e-a7db-9f516d56c7c2.png)

Suggestion: 
```css
[selector]:focus-visible {
  outline: 1px solid lighten($primary, x%);
}
```
